language: ruby
cache: bundler
rvm:
  - 2.2.2
  - 2.3.1
env:
  - "RAILS_VERSION=4.2.7"
  - "RAILS_VERSION=5.0.1"
script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - cd ../..
  - bundle exec rake
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml

notifications:
  email: false
